version: '3.7'
services:
  app:
    image: node:10-alpine
    command: 'npm run dev'
    working_dir: /usr/chapter
    volumes:
      - .:/usr/chapter
    ports:
      - '8000:8000'
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chapter
    ports:
      - '54320:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  speccy:
    image: node:10-alpine
    command: 'npm run speccy:watch'
    working_dir: /usr/chapter
    volumes:
      - .:/usr/chapter
    ports:
      - '8001:8001'
