version: '3.7'
services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '54320:5432'
  app:
    depends_on:
      - db
    image: node:10-alpine
    command: 'npm run dev'
    working_dir: /usr/chapter
    environment:
      - DB_URL=db
    #   - DB_USER=postgres
    #   - DB_PASSWORD=password
    #   - DB_NAME=chapter
    #   - CHAPTER_EMAIL=ourEmail@placeholder.place
    #   - EMAIL_USERNAME=emailUsernamePlaceholder
    #   - EMAIL_PASSWORD=emailPasswordPlaceholder
    #   - EMAIL_SERVICE=emailServicePlaceholder
    volumes:
      - .:/usr/chapter
    ports:
      - '8000:8000'
  speccy:
    image: node:10-alpine
    command: 'npm run speccy:watch'
    working_dir: /usr/chapter
    volumes:
      - .:/usr/chapter
    ports:
      - '8001:8001'
